# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'trabalho.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import crypto
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):

    def Cript(obj):
        selecionado = str(obj.comboBoxAlgoritmo.currentText())
        txtPadrao = obj.caixaTextoPadrao.toPlainText()
        txtKey = obj.caixaTextoChave.toPlainText()
        if selecionado == "Cesar":
            obj.caixaTextoCript.setPlainText(crypto.en_cesar(txtPadrao,txtKey))
        elif selecionado == "XOR":
            obj.caixaTextoCript.setPlainText(crypto.en_xor(txtPadrao,txtKey))

    def Decript(obj):
        selecionado = str(obj.comboBoxAlgoritmo.currentText())
        txtCript = obj.caixaTextoCript.toPlainText()
        txtKey = obj.caixaTextoChave.toPlainText()
        if selecionado == "Cesar":
            obj.caixaTextoPadrao.setPlainText(crypto.dec_cesar(txtCript,txtKey))
        elif selecionado == "XOR":
            obj.caixaTextoPadrao.setPlainText(crypto.dec_xor(txtCript,txtKey))

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1036, 405)
        MainWindow.setMinimumSize(QtCore.QSize(1036, 405))
        MainWindow.setStyleSheet("background-color: rgb(53, 53, 53);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setContentsMargins(-1, -1, 50, -1)
        self.verticalLayout_4.setSpacing(2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.comboBoxAlgoritmo = QtWidgets.QComboBox(self.centralwidget)
        self.comboBoxAlgoritmo.setMinimumSize(QtCore.QSize(151, 22))
        self.comboBoxAlgoritmo.setMaximumSize(QtCore.QSize(151, 22))
        self.comboBoxAlgoritmo.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.comboBoxAlgoritmo.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.comboBoxAlgoritmo.setStyleSheet("background-color: rgb(27, 27, 27);\n"
"font: 12pt \"Verdana\";\n"
"color: rgb(255, 255, 255);")
        self.comboBoxAlgoritmo.setObjectName("comboBoxAlgoritmo")
        self.comboBoxAlgoritmo.addItem("")
        self.comboBoxAlgoritmo.addItem("")
        self.comboBoxAlgoritmo.addItem("")
        self.comboBoxAlgoritmo.addItem("")
        self.comboBoxAlgoritmo.addItem("")
        self.verticalLayout_4.addWidget(self.comboBoxAlgoritmo)
        self.pushButtonCript = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonCript.setMinimumSize(QtCore.QSize(131, 26))
        self.pushButtonCript.setMaximumSize(QtCore.QSize(131, 26))
        self.pushButtonCript.setMouseTracking(False)
        self.pushButtonCript.clicked.connect(lambda: Ui_MainWindow.Cript(self))
        self.pushButtonCript.setStyleSheet("QPushButton{\n"
"background-color: rgb(27, 27, 27);\n"
"font: 12pt \"Verdana\";\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(255,255,255);\n"
"color: rgb(27, 27, 27);\n"
"}\n"
"")
        self.pushButtonCript.setObjectName("pushButtonCript")
        self.verticalLayout_4.addWidget(self.pushButtonCript)
        self.pushButtonDecript = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonDecript.setMinimumSize(QtCore.QSize(131, 26))
        self.pushButtonDecript.setMaximumSize(QtCore.QSize(131, 26))
        self.pushButtonDecript.clicked.connect(lambda: Ui_MainWindow.Decript(self))
        self.pushButtonDecript.setStyleSheet("QPushButton{\n"
"background-color: rgb(27, 27, 27);\n"
"font: 12pt \"Verdana\";\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(255,255,255);\n"
"color: rgb(27, 27, 27);\n"
"}\n"
"")
        self.pushButtonDecript.setObjectName("pushButtonDecript")
        self.verticalLayout_4.addWidget(self.pushButtonDecript)
        self.gridLayout.addLayout(self.verticalLayout_4, 2, 3, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.labelTextoCript = QtWidgets.QLabel(self.centralwidget)
        self.labelTextoCript.setMinimumSize(QtCore.QSize(201, 18))
        self.labelTextoCript.setMaximumSize(QtCore.QSize(201, 18))
        self.labelTextoCript.setStyleSheet("font: 75 12pt \"Verdana\";\n"
"color: rgb(255, 255, 255);")
        self.labelTextoCript.setObjectName("labelTextoCript")
        self.verticalLayout.addWidget(self.labelTextoCript)
        self.caixaTextoCript = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.caixaTextoCript.setMinimumSize(QtCore.QSize(751, 81))
        self.caixaTextoCript.setStyleSheet("color: rgb(255, 255, 255);")
        self.caixaTextoCript.setObjectName("caixaTextoCript")
        self.verticalLayout.addWidget(self.caixaTextoCript)
        self.gridLayout.addLayout(self.verticalLayout, 1, 0, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.textoChave = QtWidgets.QLabel(self.centralwidget)
        self.textoChave.setMinimumSize(QtCore.QSize(51, 18))
        self.textoChave.setMaximumSize(QtCore.QSize(51, 18))
        self.textoChave.setStyleSheet("font: 75 12pt \"Verdana\";\n"
"color: rgb(255, 255, 255);")
        self.textoChave.setObjectName("textoChave")
        self.verticalLayout_2.addWidget(self.textoChave)
        self.caixaTextoChave = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.caixaTextoChave.setMinimumSize(QtCore.QSize(291, 31))
        self.caixaTextoChave.setStyleSheet("color: rgb(255, 255, 255);")
        self.caixaTextoChave.setObjectName("caixaTextoChave")
        self.verticalLayout_2.addWidget(self.caixaTextoChave)
        self.gridLayout.addLayout(self.verticalLayout_2, 2, 0, 1, 1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.labelTextoPadrao = QtWidgets.QLabel(self.centralwidget)
        self.labelTextoPadrao.setMinimumSize(QtCore.QSize(161, 18))
        self.labelTextoPadrao.setMaximumSize(QtCore.QSize(161, 18))
        self.labelTextoPadrao.setStyleSheet("font: 75 12pt \"Verdana\";\n"
"color: rgb(255, 255, 255);")
        self.labelTextoPadrao.setObjectName("labelTextoPadrao")
        self.verticalLayout_3.addWidget(self.labelTextoPadrao)
        self.caixaTextoPadrao = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.caixaTextoPadrao.setMinimumSize(QtCore.QSize(751, 92))
        self.caixaTextoPadrao.setStyleSheet("color: rgb(255, 255, 255);")
        self.caixaTextoPadrao.setObjectName("caixaTextoPadrao")
        self.verticalLayout_3.addWidget(self.caixaTextoPadrao)
        self.gridLayout.addLayout(self.verticalLayout_3, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(50, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 2, 2, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.comboBoxAlgoritmo.setItemText(0, _translate("MainWindow", "Cesar"))
        self.comboBoxAlgoritmo.setItemText(1, _translate("MainWindow", "XOR"))
        self.comboBoxAlgoritmo.setItemText(2, _translate("MainWindow", "S-DES"))
        self.comboBoxAlgoritmo.setItemText(3, _translate("MainWindow", "DES"))
        self.comboBoxAlgoritmo.setItemText(4, _translate("MainWindow", "AES"))
        self.pushButtonCript.setText(_translate("MainWindow", "criptografar"))
        self.pushButtonDecript.setText(_translate("MainWindow", "descriptografar"))
        self.labelTextoCript.setText(_translate("MainWindow", "Texto Criptografado"))
        self.textoChave.setText(_translate("MainWindow", "Chave"))
        self.labelTextoPadrao.setText(_translate("MainWindow", "Texto Padrão"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
